Repository EGC-G2-tortilla/tortilla-hub, pull requests merged in 2024-11, with the labels that each got.

#4 Task/fakenodo
  app/modules/dataset/assets/scripts.js
  app/modules/dataset/routes.py
  app/modules/dataset/templates/dataset/upload_dataset.html
  app/modules/fakenodo/__init__.py
  app/modules/fakenodo/assets/scripts.js
  app/modules/fakenodo/forms.py
  app/modules/fakenodo/models.py
  app/modules/fakenodo/repositories.py
  app/modules/fakenodo/routes.py
  app/modules/fakenodo/services.py
  app/modules/fakenodo/templates/index.html
  app/modules/zenodo/.env.example
  app/modules/zenodo/__init__.py
  app/modules/zenodo/forms.py
  app/modules/zenodo/models.py
  app/modules/zenodo/repositories.py
  app/modules/zenodo/routes.py
  app/modules/zenodo/services.py
Labels: enhancement

#10 Staging area WI
  app/modules/dataset/models.py
  app/modules/dataset/repositories.py
  app/modules/dataset/routes.py
  app/modules/dataset/seeders.py
  app/modules/dataset/services.py
  app/modules/dataset/templates/dataset/list_datasets.html
  migrations/versions/001.py
  migrations/versions/a063a912d659_añadida_la_propiedad_status_a_dataset.py
Labels: enhancement

#46 Organización de las migraciones por milestone closes#45
  migrations/versions/002.py
  migrations/versions/31ef8ac73964_create_new_model_oauth.py
  migrations/versions/6f5857a1b32d_add_orcid_field_to_user_model.py
  migrations/versions/8bb175a68811_merging_migrations.py
  migrations/versions/a063a912d659_añadida_la_propiedad_status_a_dataset.py
  migrations/versions/d535906142c2_.py
Labels: bug

#27 Añadido actions que mergea las migraciones las HEAD de las migraciones
  .github/workflows/merge-migrations.yml
Labels: workflow

#51 Workflow se lanza adecuadamente para pushes en main/ develop
  .github/workflows/lint.yml
Labels: bug

#52 Seeders de dataset ahora no contienen datos repetidos closes #47
  app/modules/dataset/seeders.py
Labels: bug

#92 feat: view user profile
  app/modules/dataset/templates/dataset/view_dataset.html
  app/modules/profile/routes.py
  app/modules/profile/templates/profile/summary.html
  app/modules/profile/tests/test_selenium.py
  app/modules/profile/tests/test_unit.py
Labels: WI

#119 WI: Mejora del feedback al usuario e integración con Fakenodo
  app/modules/dataset/models.py
  app/modules/dataset/routes.py
  app/modules/dataset/services.py
  app/modules/dataset/templates/dataset/list_datasets.html
Labels: WI

#129 Pruebas unitarias y de rendimiento para la validación de archivos UVL
  CHANGELOG.md
  app/modules/flamapy/routes.py
  app/modules/flamapy/tests/locustfile.py
  app/modules/flamapy/tests/test_unit.py
Labels: WI

#122 Incidencia: Workflow de lint y formatting es lanzado correctamente en PRs
  .github/workflows/lint.yml
Labels: bug

#130 Añadidos los tests unitarios closes #104
  app/modules/dataset/tests/test_unit_staging_area.py
Labels: WI
