Repository EGC-G2-tortilla/tortilla-hub, pull requests merged in 2024-12, with the labels that each got.

#148 Feat: tests rendimiento con locust para improve ui
  app/modules/dataset/tests/locustfile.py
Labels: WI

#146 Feat: tests de selenium para la vista de detalle de los datasets
  app/modules/dataset/templates/dataset/view_dataset.html
  app/modules/dataset/tests/test_selenium.py
Labels: WI

#139 WI: Añadido poder unstagear todos los datasets simultáneamente
  app/modules/dataset/routes.py
  app/modules/dataset/services.py
  app/modules/dataset/templates/dataset/list_datasets.html
Labels: WI

#140 WI: Testing completo de la staging area closes #104
  app/modules/dataset/tests/locustfile.py
  app/modules/dataset/tests/test_selenium.py
  app/modules/dataset/tests/test_unit_staging_area.py
Labels: WI

#151 WI: Rate datasets closes #58
  app/modules/dataset/models.py
  app/modules/dataset/repositories.py
  app/modules/dataset/routes.py
  app/modules/dataset/seeders.py
  app/modules/dataset/services.py
  app/modules/dataset/templates/dataset/view_dataset.html
  app/static/css/own.css
  migrations/versions/003.py
Labels: WI

#166 Task/test sync with GitHub/Gitlab
  app/modules/auth/tests/test_unit.py
Labels: WI

#189 Feat: modificacion del workflow de dockerhub para raspberry
  .github/workflows/deployment_on_dockerhub.yml
Labels: workflow

#202 feat: Nuevo playbook de tests en Vagrant
  vagrant/00_main.yml
  vagrant/08_tests.yml
Labels: workflow

#215 WI: Mejora de la integración con Fakenodo
  app/modules/dataset/repositories.py
  app/modules/dataset/seeders.py
  app/modules/dataset/services.py
  app/modules/dataset/templates/dataset/list_datasets.html
  app/modules/dataset/tests/test_selenium.py
  app/modules/dataset/tests/test_selenium_upload_from_zip.py
  app/modules/fakenodo/models.py
  app/modules/fakenodo/repositories.py
  app/modules/fakenodo/services.py
  migrations/versions/21fee77ec676_.py
Labels: WI, fakenodo

#221 WI: FM-Fact-Label
  app/modules/dataset/models.py
  app/modules/dataset/routes.py
  app/modules/dataset/services.py
  app/modules/dataset/templates/dataset/view_dataset.html
  app/modules/featuremodel/models.py
  app/modules/featuremodel/services.py
  app/modules/flamapy/repositories.py
  app/modules/flamapy/routes.py
  app/modules/flamapy/services.py
  app/modules/hubfile/models.py
  app/modules/hubfile/routes.py
  app/modules/hubfile/services.py
  migrations/versions/26242a811df2_.py
  uploads/user_1/dataset_9/file12.uvl
Labels: WI

#245 Fix: Tests de carga de la Staging Area
  app/modules/auth/models.py
  app/modules/dataset/tests/locustfile.py
  app/modules/dataset/tests/locustfile_staging_area.py
  app/modules/dataset/tests/test_unit_staging_area.py
Labels: bug, WI

#249 test: unit test fm fact label
  app/modules/featuremodel/tests/test_unit.py
  app/modules/hubfile/models.py
Labels: WI
